name: Deno

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.5

      - name: Verify formatting
        run: deno fmt --check

      - name: Run type checker
        run: deno check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.5

      - name: Bundle website
        run: deno task build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './www'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
